# vouch config
# bare minimum to get vouch running with github

vouch:
  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  # for github that's only one domain since they only allow one callback URL
  # https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls
  # each of these domains must serve the url https://login.$domains[0] https://login.$domains[1] ...
  domains:
  - mcaq.me
  - mcadesigns.co.uk

  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at GitHub
  # allowAllUsers: true

oauth:
  # create a new OAuth application at:
  # https://github.com/settings/applications/new
  provider: github
  client_id: ${VCLIENTID:?please set a client ID}
  client_secret: ${VCLIENTSECRET:?Please set a client secret}
  # endpoints set from https://godoc.org/golang.org/x/oauth2/github