version: 2.1

jobs:
  build:
    docker:
      - image: docker:18-git

    steps:
      - setup_remote_docker

      - run:
          name: "Setup dependencies"
          command: |
            git clone https://github.com/Sharpz7/dockerfiles

      - run:
          name: "Build"
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            cd dockerfiles
            for dir in */; do
              cd "$dir"
              docker pull sharp6292/"${dir::-1}":latest || true
              docker build --cache-from sharp6292/"${dir::-1}":latest -f "Dockerfile" -t sharp6292/"${dir::-1}":latest .
              docker push sharp6292/"${dir::-1}":latest
              cd ..
            done

workflows:
  version: 2
  workflow:
    jobs:
      - build