version: 2.1

jobs:
  create:
    docker:
      - image: python:3.7.3-slim-stretch

    steps:
      - checkout

      - run:
          name: "Setup dependencies"
          command: |
            mkdir builds

      - run:
          name: Create Build Files
          command: |
            python build.py
            mkdir ./workspace
            cp -r ./builds ./workspace

      - persist_to_workspace:
          root: .
          paths:
            - ./workspace

  build:
    docker:
      - image: docker:stable

    parallelism: 4

    steps:
      - setup_remote_docker

      - checkout

      - attach_workspace:
          at: .

      - run:
          name: "Build"
          command: |
            ls ./workspace
            sh ./workspace/build-${CIRCLE_NODE_INDEX}.sh

workflows:
  version: 2
  workflow:
    jobs:
      - create
      - build:
          requires:
            - create