version: 2.1

jobs:
  create:
    docker:
      - image: python:3.7.3-slim-stretch

    steps:
      - checkout

      - run:
          name: "Setup dependencies"
          command: |
            mkdir builds

      - run:
          name: Create Build Files
          command: python build.py

      - persist_to_workspace:
          root: .
          paths:
            - ./builds
  build:
    docker:
      - image: docker:stable

    parallelism: 4

    steps:

      - setup_remote_docker

      - attach_workspace:
          at: .

      - run:
          name: "Build"
          command: |
            cd ./builds
            sh build-${CIRCLE_NODE_INDEX}.sh

workflows:
  version: 2
  workflow:
    jobs:
      - create
      - build:
          requires:
            - create