version: 2.1

jobs:
  build:
    docker:
      - image: docker:18-git

    steps:
      - setup_remote_docker

      - run:
          name: "Setup dependencies"
          command: |
            git clone https://github.com/Sharpz7/dockerfiles
            cd dockerfiles
            ls

      - run:
          name: "Build"
          command: |
            arr=./*

            for item in "${arr[@]}"; do
                $dir = "$item"
                if ($dir -ne ".circleci") && ($dir -ne "README.md"); then
                    cd $dir
                    docker pull sharp6292/${dir}:latest || true
                    docker build --cache-from sharp6292/${dir}:latest -f "Dockerfile" -t sharp6292/${dir}:latest .
                    docker push sharp6292/${dir}:latest
                    cd ..
                fi
            done

workflows:
  version: 2
  workflow:
    jobs:
      - build