version: 2.1

jobs:
  build:
    docker:
      - image: docker:18-git

    steps:
      - setup_remote_docker

      - run:
          name: "Setup dependencies"
          command: |
            git clone https://github.com/Sharpz7/dockerfiles
            cd dockerfiles

      - run:
          name: "Build"
          command: |
            arr=$(./*)

            for item in "${arr[@]}"; do
                echo "$item"
            done

workflows:
  version: 2
  workflow:
    jobs:
      - build