version: 2.1

jobs:
  create:
    docker:
      - image: python:3.7.3-slim-stretch

    steps:
      - checkout

      - run:
          name: "Setup dependencies"
          command: |
            apt-get update -y
            apt-get install -y git
            git clone https://github.com/Sharpz7/dockerfiles
            mkdir builds
            mkdir /builds

      - run:
          name: Create Build Files
          command: python build.py

      - persist_to_workspace:
          root: ./builds
          paths:
            - ./*

  build:
    machine: true

    parallelism: 4

    steps:
      - checkout

      - attach_workspace:
          at: ./builds

      - run:
          name: "Build"
          command: |
            cd /builds
            ls
            echo ${CIRCLE_NODE_INDEX}
            sh ./build-${CIRCLE_NODE_INDEX}

workflows:
  version: 2
  workflow:
    jobs:
      - create
      - build:
          requires:
            - create