version: 2.1

jobs:
  create:
    docker:
      - image: python:3.7.3-slim-stretch

    steps:
      - checkout

      - run:
          name: "Setup dependencies"
          command: |
            mkdir builds
            mkdir /builds

      - run:
          name: Create Build Files
          command: python build.py

      - persist_to_workspace:
          root: ./builds
          paths:
            - ./*

  build:
    docker:
      - image: bash:latest

    parallelism: 4

    steps:
      - attach_workspace:
          at: ./builds

      - run:
          name: "Build"
          command: |
            cd ./builds
            bash build-${CIRCLE_NODE_INDEX}.sh

workflows:
  version: 2
  workflow:
    jobs:
      - create
      - build:
          requires:
            - create